# Generated by Django 4.2.4 on 2023-08-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.IntegerField(default=0),
        ),
    ]
